### ISSUE TITLE
Saved Report feature issues 

### ISSUE THREAD

**Issue by redet-G** [HABTec/public-dashboard#136]
- [x] They do not work from `feedback` and `request-form`
- [x] Staring from saved reports and clicking on share button give us wrong share link

**Comment by RihanaE** [comment]
@redet-G, in the saved report, when there is more than one charts saved, it gives a wrong link to be shared. Could you also tell me how the saved reports are handled? Do they have their own separate page for management, or did you use another mechanism?

**Comment by redet-G** [comment]
It does not have a separate page. One of the solutions we discussed was to create a separate page and handel them that way. Whenever a user clicks on saved reports which should now be changed to a link, should redirect the user to saved reports page. When, a specific chart is clicked it should be linked to saved reports page with  a parameter similar`chart_id=`. The saved reports then should be loading it's data from the browsers data store. Handle both of the above case that is when all saved reports are display and when a specific saved chart is displayed.
