### ISSUE TITLE
Shareable link for each of the dashboards as well as the dashboard items

### ISSUE THREAD

**Issue by redet-G** [HABTec/public-dashboard#23]
Users should be able to share a page and view the exact same content without having to select the dashboard from the dropdown list. It would also be nice if we could share a dashboard item only.

**Comment by redet-G** [comment]
20654df9c57e6066df415191418d3710a2edfabb Let's try to integrate shareable dashboard item as well

**Comment by RihanaE** [comment]
Okay, I am working on it

**Comment by RihanaE** [comment]
When the user shares the dashboard item link, where will it lead? Is it going to take the user to the dashboard, where the item is currently located?

**Comment by redet-G** [comment]
It is supposed show the user the shared dashboard item only. If the dashboard for example has five dashboard items and a user shared a link to one of the items it has to display only the shared item.

**Comment by redet-G** [comment]
435df55f4d462875a8fdeb2bc95c56dc826282ed This was fast!
