### ISSUE TITLE
Orgunit level and group selectors must be changed to multi-select

### ISSUE THREAD

**Issue by redet-G** [HABTec/public-dashboard#29]
@RihanaE  We forgot to make them multi-select can you handle this? Let's fix this on feature/orgunitfilter branch

**Comment by RihanaE** [comment]
Okay, I will

**Comment by redet-G** [comment]
It would be great to notify me when you are done in the original issue. I thought you were still working on it.

**Comment by RihanaE** [comment]
Okay, I will.
