### ISSUE TITLE
Make it installable on the moblie devices

### ISSUE THREAD

**Issue by redet-G** [HABTec/public-dashboard#4]
Let's make this app installable on mobile devices. Meaning it has to be a progressive webapp.

**Comment by RihanaE** [comment]
Okay

**Comment by redet-G** [comment]
@RihanaE and update on this?

**Comment by RihanaE** [comment]
It can now be installed on mobile. I tested it using the ngrok tool, as it must be served over HTTPS to be installed on mobile devices.

￼￼

**Comment by redet-G** [comment]
This great! Next time you add features create a pull request.

**Comment by RihanaE** [comment]
Okay I will
