### ISSUE TITLE
[map] add orgunit layer

### ISSUE THREAD

**Issue by redet-G** [HABTec/public-dashboard#43]

**Comment by redet-G** [comment]
@RihanaE any update

**Comment by RihanaE** [comment]
The chartData error we experienced with the Tigray map is occurring again when trying to access the orgUnit layer. The current method for processing shapes, rows, etc., is designed for a single layer only. I am trying to find a way to achieve the same result when working with multiple layers.

**Comment by RihanaE** [comment]
Hello Redet, 

The orgUnit layer component is completed with some minor additions to the code of the thematicLayer component. However, it is not able to reach the point where the map component is being rendered.
“
{httpStatus: 'Conflict', httpStatusCode: 409, status: 'ERROR', message: 'At least one period as dimension or filter, or start and dates, must be specified', errorCode: 'E7104'}
errorCode
: 
"E7104"
httpStatus
: 
"Conflict"
httpStatusCode
: 
409
message
: 
"At least one period as dimension or filter, or start and dates, must be specified"
status
: 
"ERROR"
[[Prototype]]
: 
Object
“

The orgUnit layer implemented:

￼￼
