### ISSUE TITLE
Adding support for area chart type

### ISSUE THREAD

**Issue by redet-G** [HABTec/public-dashboard#5]
On DHIS2 there are other chart types that are not supported yet one of which is the area chart type. Example of area chart is shown in the picture below. Support lines should be added to the charts themselves.

![image](https://github.com/HABTec/public-dashboard/assets/20116752/8ab540a1-6ce3-4903-93aa-2e0a82a8b800)

**Comment by redet-G** [comment]
@RihanaE Let me know if you can handle this?

**Comment by RihanaE** [comment]
Okay, I will work on it.
