### ISSUE TITLE
support for radar chart type

### ISSUE THREAD

**Issue by redet-G** [HABTec/public-dashboard#52]
![image](https://github.com/user-attachments/assets/c15bd25d-206c-47a5-ae09-612d6389adab)

**Comment by RihanaE** [comment]
@redet-G @mui doesn't yet support radar chart. Is there any library you planned to be used?

**Comment by redet-G** [comment]
check this library https://nivo.rocks/radar/

**Comment by RihanaE** [comment]
okay
