### ISSUE TITLE
Add Orgunit filter for all chart types

### ISSUE THREAD

**Issue by redet-G** [HABTec/public-dashboard#8]

**Comment by redet-G** [comment]
`/organisationUnits/PweZnUvvtxv?fields=children%5Bid%2Cpath%2CdisplayName%5D`

**Comment by RihanaE** [comment]
This path is giving me 404 error.
“organisationUnits/PweZnUvvtxv?fields=children%5Bid%2Cpath%2CdisplayName%5D
"


On 19 Jun 2024, at 17:15, Redet Getachew ***@***.***> wrote:

organisationUnits/PweZnUvvtxv?fields=children%5Bid%2Cpath%2CdisplayName%5D

**Comment by redet-G** [comment]
This is just to show you how you may use the API. Replace {id of the orgunit } with the id of the orgunit you want to browse in
```
/api/organisationUnits/{id of the orgunit}?fileds=children[id, path, displayName]
````
You can find the id of the orgunit by hitting the following endpoint
```
/api/me?fields=dataViewOrganisationUnits
```
When you hit this endpoint it will return the following JSON. From this, you have use `dataViewOrganisationUnits.id` as the root orgunit from which you can expand to child orgunits

```JSON
{
  "dataViewOrganisationUnits": [
    {
      "id": "b3aCK1PTn5S"
    }
  ]
}

**Comment by RihanaE** [comment]
Oh okay. Thank you for the explanation

**Comment by RihanaE** [comment]
This path is giving me a 404, “Not Found" error.
“https://hmis.dhis.et/api/40/organisationUnits/PweZnUvvtxv?fields=children%5Bid%2Cpath%2CdisplayName%5D
"

**Comment by redet-G** [comment]
There is not orgunit with that id(`PweZnUvvtxv`) that is why it is returing 404

**Comment by redet-G** [comment]
[d537ff8](https://github.com/HABTec/public-dashboard/commit/d537ff8086863eb5debe9ec8ab95b421f59a7e5e)
