### ISSUE TITLE
Invalid LatLng object

### ISSUE THREAD

**Issue by RihanaE** [HABTec/public-dashboard#85]
When switching from the Choropleth map to the Bubble map, an error occurs

<img width="1440" alt="Screenshot 2024-10-13 at 18 57 58" src="https://github.com/user-attachments/assets/4c513243-5264-413f-9bae-5e1c55a8eee3">
<img width="1440" alt="Screenshot 2024-10-13 at 18 59 12" src="https://github.com/user-attachments/assets/a6dd073b-74f2-44ad-82e5-1078ceb2b69b">

**Comment by redet-G** [comment]
Hi @RihanaE 

I could not replicate it on your branch. Could you please be more specific which chart is causing the issue? An id would be helpful.

**Comment by RihanaE** [comment]
<img width="844" alt="Screenshot 2024-10-15 at 15 26 09" src="https://github.com/user-attachments/assets/5a69e1d1-3927-4d97-a100-633fb184790e">

Here is the data information on the chart

**Comment by redet-G** [comment]
I was not still able to reproduce your error on that specific chart. Is there any other commit you have not pushed to the PR?

**Comment by RihanaE** [comment]
I don't think so but I am not quite sure. Should I push the current code?

**Comment by redet-G** [comment]
Is this issue still persisting?

**Comment by RihanaE** [comment]
yes

**Comment by RihanaE** [comment]
I tried it both on another PC and on my phone, but the error persists.

![photo_2024-10-30 10 46 27](https://github.com/user-attachments/assets/50e2f50a-5281-4c8c-923f-a5859425aec3)
![photo_2024-10-30 10 46 58](https://github.com/user-attachments/assets/3f797083-1382-4f07-b362-c93ca41b99ca)

**Comment by redet-G** [comment]
Can you replicate it on http://dashboard.dhis.et?

**Comment by RihanaE** [comment]
I think the error is already present, though it's only visible in the console.

<img width="1440" alt="Screenshot 2024-10-30 at 10 58 02" src="https://github.com/user-attachments/assets/d6690087-3fae-4c71-8d36-54db6f3002ba">

**Comment by redet-G** [comment]
The issue seems to be coming from the following link of code from `useRenderMapLayers.js`
```
     const regionListIndex = viewData.regionList.indexOf(region.na);

      const dataValue =
        regionListIndex !== -1 ? viewData.mapData[0].data[regionListIndex] : 0;

      let radius = (dataValue / (legendMx - legendMn)) * 90;
```

As you can see whenever the denominator is zero the radius is set to `NaN`. And, the circle component does not accept NaN. We can simply reset radius to zero whenever this happens.

**Comment by redet-G** [comment]
let me know if this still exists after this https://github.com/HABTec/public-dashboard/commit/185355a025ce9f27352a6209ae38f18898025112

**Comment by RihanaE** [comment]
okay
