### ISSUE TITLE
Split Map view is not support yet

### ISSUE THREAD

**Issue by redet-G** [HABTec/public-dashboard#86]

**Comment by redet-G** [comment]
![image](https://github.com/user-attachments/assets/3b7b4d6c-5661-43fc-b2a5-0e2cb35654bd)
![image](https://github.com/user-attachments/assets/776a780c-ea2c-4c02-8584-c0b51b18e2e1)

It allows you to view the map individually in the form of a grid for each of the periods.

**Comment by redet-G** [comment]
One chart with multiple map views for each period

**Comment by RihanaE** [comment]
Adding split Map View legend component
Add support for Predefined Color Legend
Correct Automatic Color display
