### ISSUE TITLE
Apply opacity property of map base layer. 

### ISSUE THREAD

**Issue by redet-G** [HABTec/public-dashboard#95]
On DHIS2, there is an option to define the opacity of the base layer. Make sure that the opacity property is applied as specified by the system. 

![image](https://github.com/user-attachments/assets/c5ecbc06-d504-47d9-8729-98192a911cfc)

**Comment by RihanaE** [comment]
The system is not applying the opacity. It remains fully opaque even after you change it.

<img width="1440" alt="Screenshot 2024-10-21 at 18 25 15" src="https://github.com/user-attachments/assets/fda60968-c8c5-42d5-af23-6ea8c066f226">
<img width="1440" alt="Screenshot 2024-10-21 at 18 25 31" src="https://github.com/user-attachments/assets/5da7d1ce-a104-4475-926b-32ee1e1efc37">
